# Hyprland config adaptada de Omarchy (https://omarchy.org) para Ubuntu 26.04
# https://wiki.hypr.land/Configuring/

source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

exec-once = hyprctl setcursor default 24
