# Input - adaptado de Omarchy (todo comentado = defaults)
input {
    kb_layout = latam
    # kb_layout = us,es     # añade es y descomenta la linea de abajo para alternar con Alt+Alt
    # kb_options = grp:alts_toggle
    repeat_rate = 40
    repeat_delay = 250
    numlock_by_default = true

    touchpad {
        natural_scroll = true
        clickfinger_behavior = true
        scroll_factor = 0.4
        disable_while_typing = false
    }
}

gestures {
    workspace_swipe_touch = true
}
