# Reglas de ventana (sintaxis v3) - apps que abren flotantes y centradas

windowrule {
    name = pavucontrol-flotante
    match:class = (pavucontrol)

    float = true
    center = true
}

windowrule {
    name = blueman-flotante
    match:class = (blueman-manager)

    float = true
    center = true
}

windowrule {
    name = zenity-flotante
    match:class = (zenity)

    float = true
}
