# ==============================================================================
# Solo Leveling Palette — Kitty
# Source of truth: config/colors/palette.sh
# ==============================================================================

foreground            #ffffff
background            #252525
cursor                #ffffff
selection_background  #170830
selection_foreground  #ffffff

color0  #130728
color1  #8f45e3
color2  #8f59aa
color3  #c47be8
color4  #8f45e3
color5  #f485ed
color6  #8f45e3
color7  #fab1ed
color8  #583e53
color9  #ac53ff
color10 #ac6bcc
color11 #e18dff
color12 #b356ff
color13 #ffa6ff
color14 #ac53ff
color15 #ffbaf9
